export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "../globals.css";

import Script from "next/script";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script async src="https://tenor.com/embed.js"></Script>
    </html>
  );
}
